apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: secret-management
spec:
  provider:
    {{- if .Values.clusterSecretStore.provider.vault.enabled }}
    vault:
      server: {{ .Values.clusterSecretStore.provider.vault.server | quote }}
      path: {{ .Values.clusterSecretStore.provider.vault.path | quote }}
      version: {{ .Values.clusterSecretStore.provider.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.clusterSecretStore.provider.vault.auth.tokenSecretRef.name | quote }}
          namespace: {{ .Values.clusterSecretStore.provider.vault.auth.tokenSecretRef.namespace | quote }}
          key: {{ .Values.clusterSecretStore.provider.vault.auth.tokenSecretRef.key | quote }}
    {{- end }}
    {{- if .Values.clusterSecretStore.provider.aws.enabled }}
    aws:
      service: {{ .Values.clusterSecretStore.provider.aws.service }}
      region: {{ .Values.clusterSecretStore.provider.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.clusterSecretStore.provider.aws.auth.secretRef.accessKeyID.name }}
            namespace: {{ .Values.clusterSecretStore.provider.aws.auth.secretRef.accessKeyID.namespace }}
            key: {{ .Values.clusterSecretStore.provider.aws.auth.secretRef.accessKeyID.key }}
          secretAccessKeySecretRef:
            name: {{ .Values.clusterSecretStore.provider.aws.auth.secretRef.secretAccessKey.name }}
            namespace: {{ .Values.clusterSecretStore.provider.aws.auth.secretRef.secretAccessKey.namespace }}
            key: {{ .Values.clusterSecretStore.provider.aws.auth.secretRef.secretAccessKey.key }}
    {{- end }}
    {{- if .Values.clusterSecretStore.provider.azure.enabled }}
    azurekv:
      vaultUrl: {{ .Values.clusterSecretStore.provider.azure.vaultUrl | quote }}
      tenantId: {{ .Values.clusterSecretStore.provider.azure.tenantId | quote }}
      authSecretRef:
        clientId:
          name: {{ .Values.clusterSecretStore.provider.azure.authSecretRef.clientId.name }}
          namespace: {{ .Values.clusterSecretStore.provider.azure.authSecretRef.clientId.namespace }}
          key: {{ .Values.clusterSecretStore.provider.azure.authSecretRef.clientId.key }}
        clientSecret:
          name: {{ .Values.clusterSecretStore.provider.azure.authSecretRef.clientSecret.name }}
          namespace: {{ .Values.clusterSecretStore.provider.azure.authSecretRef.clientSecret.namespace }}
          key: {{ .Values.clusterSecretStore.provider.azure.authSecretRef.clientSecret.key }}
    {{- end }}
    {{- if .Values.clusterSecretStore.provider.gcp.enabled }}
    gcpsm:
      projectID: {{ .Values.clusterSecretStore.provider.gcp.projectID | quote }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ .Values.clusterSecretStore.provider.gcp.auth.secretRef.secretAccessKeySecretRef.name }}
            namespace: {{ .Values.clusterSecretStore.provider.gcp.auth.secretRef.secretAccessKeySecretRef.namespace }}
            key: {{ .Values.clusterSecretStore.provider.gcp.auth.secretRef.secretAccessKeySecretRef.key }}
    {{- end }}
