{{- range $name, $es := .Values.externalSecrets }}
{{- if $es.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  namespace: {{ $es.namespace }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: secret-management
    app.kubernetes.io/component: {{ $name }}
spec:
  refreshInterval: {{ $es.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $.Values.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ $es.secretName }}
    creationPolicy: Owner
  data:
    {{- range $es.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
