# Wave 1: Foundation (namespaces, RBAC)
# Must deploy first - all other apps depend on namespaces existing

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundation
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: foundation
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "REPO_URL"
    targetRevision: "TARGET_REVISION"
    path: foundation
    helm:
      valueFiles:
        # PLACEHOLDER: Replace ENVIRONMENT with dev, preprod, or prod
        - ../environments/ENVIRONMENT/foundation.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
