# Wave 2: Istio Base (CRDs and cluster resources)
# Must deploy before istiod

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "REPO_URL"
    targetRevision: "TARGET_REVISION"
    path: base
    helm:
      valueFiles:
        - ../environments/ENVIRONMENT/base.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: service-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - Replace=true
