# Wave 9: ArgoCD (GitOps CD platform)
# Note: ArgoCD manages itself after initial bootstrap

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "REPO_URL"
    targetRevision: "TARGET_REVISION"
    path: argo-cd
    helm:
      valueFiles:
        - ../environments/ENVIRONMENT/argo-cd.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
