# Wave 10: Harbor (Container registry)
# Depends on External Secrets for credentials

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "REPO_URL"
    targetRevision: "TARGET_REVISION"
    path: harbor
    helm:
      valueFiles:
        - ../environments/ENVIRONMENT/harbor.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
