# App of Apps - Root ArgoCD Application
# This is the bootstrap application that deploys all other applications.
# Apply this manually first: kubectl apply -f argocd-apps/app-of-apps.yaml
#
# IMPORTANT: Replace these placeholders before applying:
#   - REPO_URL: Your Git repository URL
#   - TARGET_REVISION: Branch/tag (e.g., main, HEAD)
#   - ENVIRONMENT: dev, preprod, or prod

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "REPO_URL"
    targetRevision: "TARGET_REVISION"
    path: argocd-apps
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
