{{- range $key, $ns := .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns.name }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: platform
    istio-injection: {{ $ns.istioInjection | default "disabled" }}
{{- end }}
{{- range .Values.workloadNamespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: workloads
    istio-injection: {{ .istioInjection | default "enabled" }}
{{- end }}
