---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-namespace-viewer
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: platform
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-secret-reader
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: platform
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-cert-manager-integration
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: platform
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "certificaterequests", "issuers", "clusterissuers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
