apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: service-mesh
spec:
  selector:
    istio: ingressgateway
  servers:
    {{- range .Values.gateway.servers }}
    - port:
        number: {{ .port }}
        name: {{ .name }}
        protocol: {{ .protocol }}
      {{- if .tls }}
      tls:
        {{- if .tls.httpsRedirect }}
        httpsRedirect: true
        {{- else }}
        mode: {{ .tls.mode }}
        credentialName: {{ .tls.credentialName }}
        {{- end }}
      {{- end }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
---
{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-tls
  namespace: {{ .Values.gateway.namespace }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: service-mesh
spec:
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    name: {{ .Values.tls.issuerRef.name }}
    kind: {{ .Values.tls.issuerRef.kind }}
  dnsNames:
    {{- range .Values.tls.hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
